# Generated by Django 4.2.7 on 2026-03-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='taxiparks/logos/', verbose_name='Логотип')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=300, verbose_name='Meta Keywords')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район Москвы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('working_hours', models.CharField(default='Круглосуточно', max_length=100, verbose_name='Часы работы')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг')),
                ('price_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена за км')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Минимальная стоимость')),
                ('has_children_seat', models.BooleanField(default=False, verbose_name='Детское кресло')),
                ('has_animal_transport', models.BooleanField(default=False, verbose_name='Перевозка животных')),
                ('has_cargo', models.BooleanField(default=False, verbose_name='Грузовое такси')),
                ('has_minivan', models.BooleanField(default=False, verbose_name='Минивэн')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Таксопарк',
                'verbose_name_plural': 'Таксопарки',
                'ordering': ['-rating', '-likes_count'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Оценка')),
                ('honeypot', models.CharField(blank=True, max_length=100, verbose_name='Honeypot')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('taxipark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='taxiparks.taxipark')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('taxipark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='taxiparks.taxipark')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'unique_together': {('taxipark', 'ip_address')},
            },
        ),
    ]
