# Generated by Django 4.2.7 on 2026-03-09 17:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiparks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxipark',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
